cdk8s-team/cdk8s-projen-common

.github/workflows/triage.yml
src/components/triage/triage.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

Fixes action failing, e.g. https://github.com/cdk8s-team/cdk8s-plus/actions/runs/4249004636

chore(triage): actions use v prefixed versions

---

.github/workflows/triage.yml
src/components/triage/triage.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

Our current workflows are [failing](https://github.com/cdk8s-team/cdk8s-dependabot-security-alerts/actions/runs/4430195739) with:
```console
The workflow is not valid. .github/workflows/triage.yml (Line: 17, Col: 9): Unexpected symbol: 'cdk8s-team/cdk8s-dependabot-security-alerts'. Located at position 22 within expression: github.repository == cdk8s-team/cdk8s-dependabot-security-alerts
```

fix(triage): repository names are malformed

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

This is required to fix build errors like:
```console
Error: Cannot find module 'node:stream'
Require stack:
- /home/runner/work/cdk8s-core/cdk8s-core/node_modules/jsii-rosetta/lib/json.js
- /home/runner/work/cdk8s-core/cdk8s-core/node_modules/jsii-rosetta/lib/tablets/tablets.js
```
Which are currently failing all our dependency upgrades because `jsii-rosetta` makes use of new API not available in 14.17.0

chore: bump node version in workflows to `16.13.0`

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

Currently seeing build errors like,
```
error lru-cache@9.0.1: The engine "node" is incompatible with this module. Expected version "14 || >=16.14". Got "16.13.0"
```
in workflow builds. Example build: https://github.com/cdk8s-team/cdk8s-cli/actions/runs/4673216881/jobs/8276206871?pr=899
This PR is updating the node version for the build.

fix: workflow builds are broken due to node version mismatch

---

.projen/deps.json
package.json
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap
yarn.lock

Now that `constructs` [uses node 16](https://github.com/aws/constructs/blob/10.x/package.json#L73) we are effectively forced to do the same.

feat: default to node 16

---

.github/workflows/upgrade-configuration-main.yml
.projenrc.ts
package.json
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

The workflow should run on latest noe LTS version.
The package should not define an `engines` requirement.
Otherwise the workflow fails when going from e.g. Node 14 -> 16

fix: upgrade-configuration workflow fails with incompatible node version

---

.github/workflows/upgrade-configuration-main.yml
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

Fixes failing [upgrade-configuration-workflows](https://github.com/cdk8s-team/cdk8s-projen-common/actions/workflows/upgrade-configuration-main.yml).
Despite being documented as `lts`, this needs to be `lts/*` to get the latest LTS version of node. 🙄 
Proof this works: https://github.com/cdk8s-team/cdk8s-projen-common/actions/runs/5643185650

fix: node version string 'lts' is wrong

---

.github/workflows/upgrade-runtime-dependencies-main.yml
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

We are seeing failures in these actions because they are on the same schedule as dev dependency upgrades. The dev dependency upgrades finish slightly faster and cause these to fail because the version required for cdk8s is higher than the dependency upgrade in this workflow.
This PR offsets this upgrade by fifteen minutes.
See [example workflow run](https://github.com/cdk8s-team/cdk8s-postgres/actions/runs/5660984217/job/15337905770).

chore: offset timing of runtime dependency upgrades

---

.github/workflows/upgrade-compiler-dependencies-main.yml
.github/workflows/upgrade-runtime-dependencies-main.yml
.projen/tasks.json
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

This is rather unintuitive, as these releases don't have any added functionality to them. Using patch is more appropriate, it is also what we used before splitting the dependency upgrade workflows.

fix: dependency upgrades were released as minor versions

---

.projen/deps.json
package.json
src/projects/jsii.ts
test/projects/__snapshots__/jsii.test.ts.snap
yarn.lock

There's no real need to bump the typescript version used by downlevel-dts. Its also unclear why they depend on a nightly unstable typescript, and we are better off operating on the stable typescript version. 
Not that all of this matters anyway because we don't emit downleveled types anyway (because we dont need to), and its unlikely we ever will.

fix: `downlevel-dts` package causes daily identical releases

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-compiler-dependencies-main.yml
.github/workflows/upgrade-dev-dependencies-main.yml
.github/workflows/upgrade-runtime-dependencies-main.yml
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

Updating workflowNodeVersion to `18.17.0` to unblock builds in PRs. This version is LTS: https://nodejs.org/en/blog/release/v18.17.0

feat: update workflowNodeVersion to 18.17.0

---

.projen/tasks.json
src/projects/node.ts

As for example seen in: https://github.com/cdk8s-team/cdk8s-hasura/pull/407
The workflow upgrades the peer dependency:
```
cdk8s-plus-27: ^2.7.61 -> ^2.7.66
```
But leaves the devDependency unchanged:
```
cdk8s-plus-27: 2.7.61
```
And then the install fails because its requirements are not satisfied.
Instead, don't upgrade peer dependencies automtically. If we need to do a peerDependency upgrade, we will do it by hand.
Fixes #

fix: isolated peer upgrades break upgrade workflows

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-compiler-dependencies-main.yml
.github/workflows/upgrade-dev-dependencies-main.yml
.github/workflows/upgrade-runtime-dependencies-main.yml
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

Currently `upgrade-configuration` workflows are failing for `cdk8s-cli`: https://github.com/cdk8s-team/cdk8s-cli/actions/runs/6998871953.
This is due to us editing the workflow file and adding `lts/*` based on step number. This step number changes if we have `workflow bootstrap steps`, which would [precede](https://github.com/projen/projen/blob/da981a3e2651344ef2cc342708e67c75c0433c02/src/javascript/node-project.ts#L974C9-L974C9) node step. This results in us editing the file at the incorrect spot and lead to an incorrect workflow yaml file. 
Instead of editing the workflow file and relying on the step number to be correct, I am instead adding this to `workflowNodeVersion` property of projen projects.

chore: update workflowNodeVersion to lts/*

---

src/projects/node.ts
src/projects/typescript.ts

The newest jsii requires running on Node 18.12:
```
error jsii@5.3.7: The engine "node" is incompatible with this module. Expected version ">= 18.12.0". Got "16.20.2"
```
Upgrade all cdk8s workflows.

fix: minimum workflow Node to 18.12

---

.projen/deps.json
.projenrc.ts
package.json
yarn.lock

Must use `>=0.79 <1` syntax, instead of `^` syntax for `0.*` versions.

chore: fix the projen peerDependency range

---

.projenrc.ts
yarn.lock

Because of an incorrect peerDependency range, this package prevents projen from being updated to modern versions.
This is a re-roll of
https://github.com/cdk8s-team/cdk8s-projen-common/pull/704, but using a commit message that actually forces a release of a new version of this package.

fix: `projen-common` prevents `projen` upgrades

---

.projen/tasks.json
src/projects/node.ts
test/projects/jsii.test.ts
test/projects/node.test.ts
test/projects/typescript.test.ts

I had previously thought that since bundled dependencies eventually end up as runtime dependencies in the `package.json`, it wasn't necessary to explicitly configure them. But the constructions of the dependencies list happens because projen puts those into runtime deps.

fix: bundled dependencies were not considered as runtime

---

.projen/tasks.json
src/projects/node.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

This might actually a bug in ncu, but with the previous configuration ncu only proposed to update the peer dependency constraint to`^0` (which is later reverted by projen) and does not attempt to update the dev dep constraint.
This fix makes `ncu` not look at the projen peer dependency, because it is hardcoded anyway.
Tested locally on a previous commit:

fix(node): projen upgrades not working

---

src/components/backport/backport.ts
test/projects/__snapshots__/jsii.test.ts.snap
test/projects/__snapshots__/node.test.ts.snap
test/projects/__snapshots__/typescript.test.ts.snap

We were pinning because of [this issue](https://github.com/sqren/backport/issues/451), but it is now very old and a new major version has been released so its probably resolved. 
I also tested locally that it works fine with the new major version.

fix: remove pinning of `backport`

---

README.md

This was implemented in https://github.com/cdk8s-team/cdk8s-projen-common/pull/961 but mistakenly marked as a `chore` so it wasn't released. Dummy commit to roll it out.

feat: issues are tracked only in the `cdk8s` repository
